packages:
  - packages/*
  - examples/*
  - '!examples/taro-app-linaria'
  - apps/*
catalog:
  postcss: ^8.5.29
  vitest: ~5.0.3
minimumReleaseAge: 0
pmOnFail: error
versioning:
  changelog:
    storage: repository
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  core-js: false
  core-js-pure: false
  esbuild: true
  msgpackr-extract: true
  sharp: true
  swiper: false
  vue-demi: true
  workerd: true
  weapp-tailwindcss: false
overrides:
  postcss-selector-parser: 7.1.6
