import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { createContext } from '@/core/context'

const oldHelpers = path.resolve(
  __dirname,
  'fixtures/app/styled-system/helpers.mjs',
)
const panda2Helpers = path.resolve(
  __dirname,
  'fixtures/app/styled-system/helpers.panda2.mjs',
)

async function createProject(extension: 'mjs' | 'js' = 'mjs') {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'weapp-panda-'))
  await fs.symlink(
    path.resolve(__dirname, '../node_modules'),
    path.join(root, 'node_modules'),
    process.platform === 'win32' ? 'junction' : 'dir',
  )
  await fs.writeFile(
    path.join(root, 'panda.config.ts'),
    `import { defineConfig } from '@pandacss/dev'\n\nexport default defineConfig({ outdir: 'styled-system', outExtension: '${extension}' })\n`,
  )
  await fs.mkdir(path.join(root, 'styled-system'), { recursive: true })
  await fs.copyFile(
    extension === 'mjs' ? oldHelpers : panda2Helpers,
    path.join(root, `styled-system/helpers.${extension}`),
  )
  return root
}

describe('context', () => {
  it('requires a Panda config', async () => {
    await expect(createContext()).rejects.toThrow()
  })

  it.each(['mjs', 'js'] as const)('codegens and rolls back helpers.%s', async (extension) => {
    const root = await createProject(extension)
    try {
      const ctx = await createContext({ pandaConfig: { cwd: root } })
      const helper = path.join(root, `styled-system/helpers.${extension}`)
      const backup = path.join(root, `styled-system/_helpers.backup.${extension}`)
      const original = await fs.readFile(helper, 'utf8')

      await ctx.codegen()
      expect(await fs.readFile(helper, 'utf8')).not.toBe(original)
      expect(await fs.readFile(backup, 'utf8')).toBe(original)
      expect(await fs.stat(path.join(root, `styled-system/weapp-panda/index.${extension}`))).toBeDefined()
      const patched = await fs.readFile(helper, 'utf8')
      expect(patched).toContain(`./weapp-panda/index.${extension}`)
      const generated = [helper, path.join(root, `styled-system/weapp-panda/index.${extension}`), path.join(root, 'styled-system/weapp-panda/lib/index.mjs')]
      const timestamp = new Date('2000-01-01T00:00:00Z')
      for (const file of generated) {
        await fs.utimes(file, timestamp, timestamp)
      }
      await ctx.codegen()
      for (const file of generated) {
        expect((await fs.stat(file)).mtimeMs).toBe(timestamp.getTime())
      }
      expect(await fs.readFile(helper, 'utf8')).toBe(patched)
      expect(await fs.readFile(backup, 'utf8')).toBe(original)

      await ctx.rollback()
      expect(await fs.readFile(helper, 'utf8')).toBe(original)

      const regenerated = `${original}\n// regenerated by Panda\n`
      await fs.writeFile(helper, regenerated)
      await ctx.codegen()
      await ctx.rollback()
      expect(await fs.readFile(helper, 'utf8')).toBe(regenerated)
    }
    finally {
      await fs.rm(root, { recursive: true, force: true })
    }
  })

  it('rejects a missing runtime helper', async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), 'weapp-panda-'))
    try {
      await fs.symlink(
        path.resolve(__dirname, '../node_modules'),
        path.join(root, 'node_modules'),
        process.platform === 'win32' ? 'junction' : 'dir',
      )
      await fs.writeFile(
        path.join(root, 'panda.config.ts'),
        `import { defineConfig } from '@pandacss/dev'\nexport default defineConfig({ outdir: 'styled-system' })\n`,
      )
      await expect((await createContext({ pandaConfig: { cwd: root } })).codegen())
        .rejects
        .toThrow('helpers')
    }
    finally {
      await fs.rm(root, { recursive: true, force: true })
    }
  })

  it('initializes the user config in the project root', async () => {
    const root = await createProject()
    try {
      const ctx = await createContext({ pandaConfig: { cwd: root } })
      await ctx.init()
      await expect(fs.stat(path.join(root, 'weapp-pandacss.config.ts'))).resolves.toBeDefined()
    }
    finally {
      await fs.rm(root, { recursive: true, force: true })
    }
  })
})
